import json
import pprint
from pathlib import Path
from typing import Dict


def import_dbn_from_json(module_name: str) -> Dict:
    """ Import DBN from JSON generated by parsing a Python AST. """
    filename = (Path(__file__).parent/'..'/'..'/'data'/'program_analysis'/
                    module_name).resolve()

    with open(filename) as f:
        data = json.load(f)

    return data


if __name__ == '__main__':
    module_name = 'crop_yield_delphi.json'
    data = import_dbn_from_json(module_name)
    print('DELPHI_JSON:')
    pprint.pprint(data)
